// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Venjix.Infrastructure.DAL;

namespace Venjix.Migrations
{
    [DbContext(typeof(VenjixContext))]
    partial class VenjixContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Venjix.Infrastructure.DAL.Recording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("RecordingId");

                    b.HasIndex("SensorId");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("Venjix.Infrastructure.DAL.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiField")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.HasKey("SensorId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Venjix.Infrastructure.DAL.Trigger", b =>
                {
                    b.Property<int>("TriggerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContinuousSend")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Event")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<int?>("WebhookId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TriggerId");

                    b.HasIndex("SensorId");

                    b.HasIndex("WebhookId");

                    b.ToTable("Triggers");
                });

            modelBuilder.Entity("Venjix.Infrastructure.DAL.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "$2y$12$XIMeV8tAOoC7D0XRJF5TjOQNy0T9Wj71JkETAdEmrjH6X9nIf50ZO",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Venjix.Infrastructure.DAL.Webhook", b =>
                {
                    b.Property<int>("WebhookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyFormat")
                        .HasColumnType("TEXT");

                    b.Property<bool>("JsonBody")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UriFormat")
                        .HasColumnType("TEXT");

                    b.HasKey("WebhookId");

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("Venjix.Infrastructure.DAL.Recording", b =>
                {
                    b.HasOne("Venjix.Infrastructure.DAL.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Venjix.Infrastructure.DAL.Trigger", b =>
                {
                    b.HasOne("Venjix.Infrastructure.DAL.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Venjix.Infrastructure.DAL.Webhook", "Webhook")
                        .WithMany("Triggers")
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
