name: .NET Core Frontend App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Install dependencies
      working-directory: ./frontend
      run: dotnet restore

    - name: Build
      working-directory: ./frontend
      run: dotnet build --configuration Release --no-restore

    - name: Test
      working-directory: ./frontend
      run: dotnet test --no-restore --verbosity normal
